### ISSUE TITLE
procedural_function not allowing body

### ISSUE THREAD

**Issue by nonara** [PSSTools/pssparser#1]
Hi Matthew.

First, thanks for the great work. I'm implementing pss DSL 2.0 via ANTLR4 with a project, and I ran into an issue with target functions while using this grammar.

I looked in the grammar files and found the `FIXME` tag, and noticed that `procedural_stmt` was commented out between the braces. I also noticed that the vscode extension you wrote have does not have the same issue, though I see the grammar files are older.

I was hoping you might be able to provide some detail as to what was going on there and why that line needed to be commented out.

Any other knowledge you might have on other non-working parts would be most appreciated as well, if anything comes to mind. I'd be happy to submit a PR with the changes, if you'd like.

Thank you again!

**Comment by henry-czh** [comment]
这是来自QQ邮箱的自动回复邮件。

您好，您的邮件我已收到，我会尽快查收并回复。

**Comment by mballance** [comment]
Hi Ron,
    Thanks for reaching out on this. The official PSS grammar focuses on readability/understandability over being able to be implemented efficiently. I think there was sufficient ambiguity around procedural_function body that even ANTLR4 choked. 
    Looks like this is one of the ambiguities I didn't get resolved in this version of the parser As far as I can tell, I corrected the ambiguity in my 'other' version of the grammar (it's a PSS+ grammar, so not directly applicable). Let me investigate and get this version of the grammar updated. 
    Thanks again for raising this!

**Comment by nonara** [comment]
Thanks, Michael! 

I greatly appreciate it. I'm a bit new to PSS grammar, so I'm still learning all of the various edges. Your libraries have been a tremendous help in getting up to speed more quickly.

I'll keep an eye out for your changes!

**Comment by mballance** [comment]
Hi Ron,
    Have a look at the latest commit [d042e76](https://github.com/PSSTools/pssparser/commit/d042e76e2ae6b4590b7d019347e3ab0cb4655150). I've rolled in disambiguation fixes that enable ANTLR to work well. Let me know if you run into further issues!

**Comment by nonara** [comment]
Looks good. Thanks again, Matthew!
